# Generated by Django 5.2 on 2025-04-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_property_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='action',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Sold', 'Sold')], default='Ongoing', max_length=20),
        ),
    ]
