# Generated by Django 5.2 on 2025-04-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_property_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='transaction_date',
            field=models.CharField(blank=True, default=None, editable=False, max_length=20, null=True),
        ),
    ]
