# Generated by Django 5.2 on 2025-04-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_property_created_date_property_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='transaction_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
